name: Test

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  build-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install cmake gcovr ninja-build -y
      - name: Run tests with coverage options
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd src
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON
          cmake --build . -- -j$(nproc)
          ctest
          cmake --build . --target coverage
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN} -f build/coverage.info
